site_name: Requisitos - Yellow
site_url: https://yellow.netlify.com
repo_name: Requisitos/Yellow
repo_url: https://github.com/Requisitos-2019-2-Yellow/Yellow
#edit_uri: "blob/master/docs"
site_description: Requisito do aplicativo Yellow

site_author: Grupo 4

nav:
    - Planejamento do Grupo: 
        - Cronograma: planejamento_grupo/cronograma.md
        - Disponibilidade Integrantes: planejamento_grupo/timetable.md
    - Pontos de Controle: pontos_de_controle/pontos_de_controle.md 
    - Home: index.md
    - Pré-rastreabilidade:
        - Rich Picture: pre_rastreabilidade/rich_picture.md
    - Elicitação:
        - Requisitos: 
            - Brainstorm: elicitacao/requisitos/brainstorm.md
            - Requisitos Elicitados: elicitacao/requisitos/requisitos.md

theme:
  palette:
      primary: 'grey'
      accent: 'yellow'
  name: 'material'
  language: 'pt'
  favicon: '/img/icon-round.png'
  logo: '/img/icon-round.png'
