site_name: Requisitos - Yellow
site_url: https://yellow.netlify.com
repo_name: Requisitos/Yellow
repo_url: https://github.com/Requisitos-2019-2-Yellow/Yellow
#edit_uri: "blob/master/docs"
site_description: Requisito do aplicativo Yellow

site_author: Grupo 4

nav:
    - Planejamento do Grupo: 
        - Cronograma: planejamento_grupo/cronograma.md
        - Disponibilidade Integrantes: planejamento_grupo/timetable.md 
    - Home: index.md
    - Pré-rastreabilidade:
        - Rich Picture: pre_rastreabilidade/rich_picture.md

theme:
  palette:
      primary: 'grey'
      accent: 'yellow'
  name: 'material'
  language: 'pt'
  favicon: 'https://raw.githubusercontent.com/Requisitos2-2019/Yellow-Grupo-4/master/img/icon-round.png'
  logo: 'https://raw.githubusercontent.com/Requisitos2-2019/Yellow-Grupo-4/master/img/icon-round.png'
