site_name: Requisitos - Yellow
site_url: https://yellow.netlify.com
repo_name: Requisitos/Yellow
repo_url: https://github.com/Requisitos-2019-2-Yellow/Yellow

site_description: Requisitos do aplicativo Yellow

site_author: Grupo 4

nav:
    - Planejamento do Grupo:
        - Cronograma: planejamento_grupo/cronograma.md
        - Disponibilidade Integrantes: planejamento_grupo/timetable.md
    - Pontos de Controle: pontos_de_controle/pontos_de_controle.md
    - Home: index.md
    - Pré-rastreabilidade:
        - Rich Picture: pre_rastreabilidade/rich_picture.md
    - Requisitos:

        - Elicitação:
            - 5W2H:
                - 5W2H v0: elicitacao/requisitos/5w2h_v0.md
                - 5W2H v1: elicitacao/requisitos/5w2h_v1.md
            - Análise de Discurso: elicitacao/requisitos/analise_discurso.md
            - Análise de Protócolo: elicitacao/requisitos/analise_protocolo.md
            - Brainstorming:
                - Brainstorming v0: elicitacao/requisitos/brainstorm_v0.md
                - Brainstorming v1: elicitacao/requisitos/brainstorm_v1.md
            - Entrevista: elicitacao/requisitos/entrevista.md
            - Gestão de Qualidade Total: elicitacao/requisitos/gestaoqualidade.md
            - Introspecção: elicitacao/requisitos/introspeccao.md
            - Observação: elicitacao/requisitos/observacao.md
            - Prototipação: elicitacao/requisitos/prototipacao.md
            - Questionário: elicitacao/requisitos/questionario.md
            - Personas: elicitacao/requisitos/personas.md
            - Storyboard: elicitacao/requisitos/storyboard.md
            - Storytelling:
                - Storytelling v0: elicitacao/requisitos/storytelling_v0.md
                - Storytelling v1: elicitacao/requisitos/storytelling_v1.md
            - Requisitos Elicitados:
                - Requisitos v1: elicitacao/requisitos/requisitos_elicitados/requisitos_elicitados_v1.md
                - Requisitos v2: elicitacao/requisitos/requisitos_elicitados/requisitos_elicitados_v2.md
                - Requisitos v3: elicitacao/requisitos/requisitos_elicitados/requisitos_elicitados_v3.md

        - Priorização:
            - MoSCoW:
              - MoSCoW_v1: elicitacao/priorizacao/moscow.md
              - MoSCoW_v2: elicitacao/priorizacao/moscow_v2.md
            - First Things First: elicitacao/priorizacao/first_things_first.md
            - QFD-House of Quality: elicitacao/priorizacao/qfd.md

    - Modelagem:
        - Ágil:
            - Ágil v1: modelagem/agil.md
            - Ágil v2: modelagem/agil_v2.md
        - Casos de Uso:
            - Casos de Uso v1: modelagem/casos_de_uso.md
            - Casos de Uso v2: modelagem/casos_de_uso_v2.md
        - Cenários: modelagem/cenarios.md
        - Especificação Suplementar: modelagem/especificacao_suplementar.md
        - Léxicos: modelagem/lexicos.md
        - NFR Framework:
            - NFR: modelagem/nfr_framework/nfr.md
            - Confiabilidade: modelagem/nfr_framework/confiabilidade.md
            - Desempenho: modelagem/nfr_framework/desempenho.md
            - Geral: modelagem/nfr_framework/geral.md
            - Interface: modelagem/nfr_framework/interface.md
            - Usabilidade: modelagem/nfr_framework/usabilidade.md



theme:
  palette:
      primary: 'black'
      accent: 'yellow'
  name: 'material'
  language: 'pt'
  favicon: '/img/icon-round.png'
  logo: '/img/icon-round.png'
